// Code generated by MockGen. DO NOT EDIT.
// Source: metarial_service.go

// Package mold is a generated GoMock package.
package mold

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMaterialService is a mock of MaterialService interface
type MockMaterialService struct {
	ctrl     *gomock.Controller
	recorder *MockMaterialServiceMockRecorder
}

// MockMaterialServiceMockRecorder is the mock recorder for MockMaterialService
type MockMaterialServiceMockRecorder struct {
	mock *MockMaterialService
}

// NewMockMaterialService creates a new mock instance
func NewMockMaterialService(ctrl *gomock.Controller) *MockMaterialService {
	mock := &MockMaterialService{ctrl: ctrl}
	mock.recorder = &MockMaterialServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMaterialService) EXPECT() *MockMaterialServiceMockRecorder {
	return m.recorder
}

// GetMaterial mocks base method
func (m *MockMaterialService) GetMaterial(requirements []*MaterialRequirement) (Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", requirements)
	ret0, _ := ret[0].(Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial
func (mr *MockMaterialServiceMockRecorder) GetMaterial(requirements interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockMaterialService)(nil).GetMaterial), requirements)
}
