// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mold is a generated GoMock package.
package mold

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ImportFrom mocks base method
func (m *MockService) ImportFrom(path, dstName string) (*Mold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportFrom", path, dstName)
	ret0, _ := ret[0].(*Mold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportFrom indicates an expected call of ImportFrom
func (mr *MockServiceMockRecorder) ImportFrom(path, dstName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportFrom", reflect.TypeOf((*MockService)(nil).ImportFrom), path, dstName)
}
